<?php
/**
 * @var $this Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if IE 8]> <html class="no-js ie ie8" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie ie9" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-popup<?php echo $this->getBodyClass()?$this->getBodyClass() : ''?>">
	<div class="popup-wrapper">
	    <?php echo $this->getChildHtml('after_body_start') ?>
	    <?php echo $this->getChildHtml('content') ?>
	    <?php echo $this->getChildHtml('before_body_end') ?>
	</div>
	<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
